[package]
name = "kyward-ui"
version = "0.1.0"
edition = "2018"

[package.metadata.raze]
workspace_path = "//kyward-ui"
package_aliases_dir = "."
targets = [
    "wasm32-unknown-unknown",
]
genmode = "Remote"

[dependencies]
yew = "0.18"
yew-router = "0.15.0"
ybc = "0.2"