name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Push to codecov.io
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        rustup default nightly
        rustup target add wasm32-unknown-unknown

        cd ~/.cargo/bin/trunk && \
        curl https://github.com/thedodd/trunk/releases/download/v0.13.1/trunk-x86_64-unknown-linux-gnu.tar.gz \
          | tar -xzf- && \
        curl https://github.com/xd009642/tarpaulin/releases/download/0.18.2/cargo-tarpaulin-0.18.2-travis.tar.gz \
          | tar -xzf- 
        make dev.ui.build
        cargo tarpaulin --out Xml

        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.7.0
      with:
        platforms: linux/amd64 #,linux/arm64
        pull: true
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/kyward:latest
